name: Run Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Node.js Install
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Dependencies Install
        run: npm install

      - name: Jest Tests
        run: npm run test

      - name: Write .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build Project
        run: |
          npm run build-css
          npm run build

      - name: Start Server
        run: npm start &
        env:
          NODE_ENV: test

      - name: Wait for Server
        run: npx wait-on http://localhost:3000 --timeout 30000

      - name: Cypress tests
        run: npx cypress run